[lint]
# Suppress E402 (module level imports not at top) for main entry point scripts
# where sys.path manipulation is required before imports
[lint.per-file-ignores]
"lightfast_mcp_manager.py" = ["E402"]
"examples/*.py" = ["E402"]
"scripts/*.py" = ["E402"] 