[project]
name = "lightfast-mcp"
version = "0.0.1"
description = "Lightfast integration through the Model Context Protocol"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Jeevan Pillay", email = "jp@lightfast.ai"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mcp[cli]>=1.3.0",
]

[project.optional-dependencies]
dev = [
    "ruff",
]

[project.scripts]
lightfast-mock-server = "lightfast_mcp.mock_server:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"lightfast_mcp" = "src/lightfast_mcp"}

[project.urls]
"Homepage" = "https://github.com/lightfastai/lightfast-mcp"
"Bug Tracker" = "https://github.com/lightfastai/lightfast-mcp/issues"

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "UP",
    "B",
    "C4",
    "SIM",
]
ignore = []

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false
