[project]
name = "lightfast-mcp"
version = "0.0.1"
description = "Lightfast integration through the Model Context Protocol"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Jeevan Pillay", email = "jp@lightfast.ai"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mcp[cli]>=1.3.0",
    "rich",
    "requests",
    "websockets",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "taskipy",
    "pytest",
    "pytest-asyncio",
]

[project.scripts]
lightfast-mock-server = "lightfast_mcp.servers.mock_server:main"
lightfast-blender-server = "lightfast_mcp.servers.blender_mcp_server:main"
lightfast-photoshop-server = "lightfast_mcp.servers.photoshop_mcp_server:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["lightfast_mcp", "lightfast_mcp.servers", "lightfast_mcp.utils"]

[project.urls]
"Homepage" = "https://github.com/lightfastai/lightfast-mcp"
"Bug Tracker" = "https://github.com/lightfastai/lightfast-mcp/issues"

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "UP",
    "B",
    "C4",
    "SIM",
]
ignore = []

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.taskipy.tasks]
lint = "ruff check ."
format = "ruff format ."
check_format = "ruff format --check ."
fix = "ruff check . --fix && ruff format ."
mock_server = "python -m lightfast_mcp.servers.mock_server"
blender_server = "python -m lightfast_mcp.servers.blender_mcp_server"
photoshop_server = "python -m lightfast_mcp.servers.photoshop_mcp_server"
test = "pytest"
