name: Python CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Default, needed for checkout

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" # Use a single version for linting

    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Lint with Ruff
      run: nox -s lint

    - name: Type check
      run: nox -s typecheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against the Python version your project uses
        # uv will use the version specified in your project (e.g., .python-version or pyproject.toml)
        # If not pinned, you can specify like python-version: ['3.13']
        python-version: ["3.10", "3.11", "3.12", "3.13"] # Specify your target Python version for uv to use

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Run tests
      run: nox -s test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" # Use a single version for building

    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Build package
      run: nox -s build 