name: Python CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Default, needed for checkout

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against the Python version your project uses
        # uv will use the version specified in your project (e.g., .python-version or pyproject.toml)
        # If not pinned, you can specify like python-version: ['3.13']
        python-version: ["3.13"] # Specify your target Python version for uv to use

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        # Optional: specify uv version, otherwise latest is used
        # uv-version: '0.1.30'
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv pip install -e ".[dev]"

    - name: Lint with Ruff
      run: task lint # Or directly: ruff check .

    - name: Check formatting with Ruff
      run: task check_format # Or directly: ruff format --check .

    - name: Run tests with pytest
      run: task test # Or directly: pytest 