name: Validate Renovate Config

on:
  push:
    paths:
      - 'renovate.json'
  pull_request:
    paths:
      - 'renovate.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Validate Renovate Config
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: 'renovate.json' 